spring:
  application:
    name: eurekaClient

server:
  port: 8083
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka
    enabled: true
  instance:
    statusPageUrlPath: http://localhost:8083/status
    homePageUrl: http://localhost:8083/status
